-- liquibase formatted sql

--changeset akupriyanov:1
CREATE TABLE card (
id BIGINT PRIMARY KEY,
number_card VARCHAR NOT NULL UNIQUE,
cardholder VARCHAR (100),
data_active INTEGER,
status_card TEXT,
card_balance DOUBLE,
);

--changeset akupriyanov:2
CREATE TABLE client (
id BIGINT PRIMARY KEY,
name VARCHAR(100),
password VARCHAR(30),
roles TEXT,
);

--changeset akupriyanov:3
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
);